-- TalentAI Database Schema - Initial Migration
-- Version: 1.0.0
-- Description: Creates core tables for talent acquisition platform including
--              jobs, candidates, applications, assessments, offers, and agent logs

-- ============================================
-- EXTENSIONS
-- ============================================

-- Enable UUID generation functions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================
-- CORE TABLES
-- ============================================

-- Profiles: Extends Supabase auth.users with application-specific user data
-- Links to auth.users via foreign key on id
CREATE TABLE public.profiles (
    id UUID REFERENCES auth.users(id) PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    full_name VARCHAR(255),
    avatar_url VARCHAR(500),
    role VARCHAR(50) DEFAULT 'recruiter', -- admin, hiring_manager, recruiter, interviewer
    company_id UUID,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Jobs: Job postings with structured requirements and AI-generated fields
CREATE TABLE public.jobs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    title VARCHAR(255) NOT NULL,
    department VARCHAR(100),
    location VARCHAR(255),
    job_type VARCHAR(50) DEFAULT 'full-time', -- full-time, part-time, contract, internship
    remote_policy VARCHAR(50) DEFAULT 'hybrid', -- remote, hybrid, onsite
    summary TEXT,
    description TEXT,
    responsibilities JSONB DEFAULT '[]'::jsonb,
    qualifications JSONB DEFAULT '{"required": [], "preferred": []}'::jsonb,
    skills_matrix JSONB DEFAULT '{"required": [], "nice_to_have": []}'::jsonb,
    evaluation_criteria JSONB DEFAULT '[]'::jsonb,
    suggested_questions JSONB DEFAULT '{"technical": [], "behavioral": [], "situational": []}'::jsonb,
    salary_range JSONB DEFAULT '{"min": null, "max": null, "currency": "USD"}'::jsonb,
    status VARCHAR(50) DEFAULT 'draft', -- draft, active, paused, closed, filled
    created_by UUID REFERENCES public.profiles(id),
    approved_by UUID REFERENCES public.profiles(id),
    approved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Candidates: Applicant profiles with parsed resume data
CREATE TABLE public.candidates (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    email VARCHAR(255) UNIQUE NOT NULL,
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    phone VARCHAR(50),
    linkedin_url VARCHAR(500),
    linkedin_data JSONB, -- cached LinkedIn profile data
    resume_url VARCHAR(500), -- Supabase Storage path
    resume_parsed JSONB, -- extracted/structured resume data
    source VARCHAR(50) DEFAULT 'direct', -- linkedin, referral, direct, job_board
    source_details VARCHAR(255), -- specific job board, referrer name, etc.
    tags JSONB DEFAULT '[]'::jsonb,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Applications: Junction table linking candidates to jobs with screening results
CREATE TABLE public.applications (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    job_id UUID REFERENCES public.jobs(id) ON DELETE CASCADE,
    candidate_id UUID REFERENCES public.candidates(id) ON DELETE CASCADE,
    status VARCHAR(50) DEFAULT 'new', -- new, screening, shortlisted, assessment, offer, hired, rejected, withdrawn

    -- Screening results (populated by Talent Screener agent)
    screening_score DECIMAL(5,2),
    screening_recommendation VARCHAR(50), -- strong_match, good_match, partial_match, weak_match
    screening_notes JSONB,
    match_breakdown JSONB, -- detailed skill matches
    strengths JSONB DEFAULT '[]'::jsonb,
    gaps JSONB DEFAULT '[]'::jsonb,
    red_flags JSONB DEFAULT '[]'::jsonb,

    -- Stage tracking for pipeline visualization
    current_stage VARCHAR(50) DEFAULT 'new',
    stage_history JSONB DEFAULT '[]'::jsonb, -- [{stage, timestamp, actor}]

    -- Timestamps for analytics and tracking
    applied_at TIMESTAMPTZ DEFAULT NOW(),
    screened_at TIMESTAMPTZ,
    shortlisted_at TIMESTAMPTZ,
    assessed_at TIMESTAMPTZ,
    offered_at TIMESTAMPTZ,
    hired_at TIMESTAMPTZ,
    rejected_at TIMESTAMPTZ,
    rejection_reason VARCHAR(255),

    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),

    UNIQUE(job_id, candidate_id)
);

-- Assessments: Video/technical assessments with AI analysis
CREATE TABLE public.assessments (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    application_id UUID REFERENCES public.applications(id) ON DELETE CASCADE,
    assessment_type VARCHAR(50) DEFAULT 'video', -- video, technical, take_home

    -- Questions generated by Talent Assessor agent
    questions JSONB DEFAULT '[]'::jsonb,
    -- [{question_id, question_type, question_text, time_limit, rubric, key_topics}]

    -- Scheduling integration
    scheduled_at TIMESTAMPTZ,
    scheduled_duration_minutes INTEGER DEFAULT 30,
    calendar_event_id VARCHAR(255),

    -- Video assessment data
    video_url VARCHAR(500), -- Supabase Storage path
    video_duration_seconds INTEGER,

    -- AI analysis results from Gemini Vision
    video_analysis JSONB,
    -- {response_analysis: [], communication_assessment: {}, behavioral_assessment: {}}

    response_scores JSONB DEFAULT '[]'::jsonb,
    overall_score DECIMAL(5,2),
    recommendation VARCHAR(50), -- STRONG_YES, YES, MAYBE, NO
    confidence_level VARCHAR(20), -- high, medium, low

    -- Summary for quick review
    summary JSONB,
    -- {top_strengths: [], areas_of_concern: [], hiring_recommendation: ""}

    -- Status tracking
    status VARCHAR(50) DEFAULT 'pending', -- pending, scheduled, in_progress, completed, analyzed, expired
    completed_at TIMESTAMPTZ,
    analyzed_at TIMESTAMPTZ,

    -- Feature flags
    behavioral_analysis_enabled BOOLEAN DEFAULT true,

    -- Candidate access (token-based, no auth required)
    access_token VARCHAR(255) UNIQUE,
    token_expires_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Offers: Compensation packages generated by Offer Generator agent
CREATE TABLE public.offers (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    application_id UUID REFERENCES public.applications(id) ON DELETE CASCADE,

    -- Compensation details
    base_salary DECIMAL(12,2) NOT NULL,
    currency VARCHAR(10) DEFAULT 'USD',
    signing_bonus DECIMAL(12,2) DEFAULT 0,
    annual_bonus_target DECIMAL(5,2), -- percentage

    -- Equity package
    equity_type VARCHAR(50), -- options, rsu, none
    equity_amount DECIMAL(10,4), -- shares or percentage
    equity_vesting_schedule VARCHAR(100), -- "4 years with 1 year cliff"

    -- Benefits list
    benefits JSONB DEFAULT '[]'::jsonb,
    -- [{benefit_type, description, value_estimate}]

    -- Timing
    start_date DATE,
    offer_expiry_date DATE,

    -- Generated documents
    offer_letter_url VARCHAR(500),
    contract_url VARCHAR(500),

    -- Conditional requirements
    contingencies JSONB DEFAULT '[]'::jsonb, -- ["background_check", "reference_check"]

    -- Negotiation support
    negotiation_notes JSONB DEFAULT '[]'::jsonb,
    negotiation_guidance JSONB, -- {salary_flexibility: {min, max}, other_levers: []}

    -- Status workflow
    status VARCHAR(50) DEFAULT 'draft', -- draft, pending_approval, approved, sent, viewed, accepted, rejected, negotiating, expired

    -- Approval tracking
    approved_by UUID REFERENCES public.profiles(id),
    approved_at TIMESTAMPTZ,

    -- Delivery and response tracking
    sent_at TIMESTAMPTZ,
    viewed_at TIMESTAMPTZ,
    responded_at TIMESTAMPTZ,
    response_notes TEXT,

    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Agent Logs: Audit trail for all AI agent actions
CREATE TABLE public.agent_logs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    agent_type VARCHAR(50) NOT NULL, -- jd_assist, screener, assessor, offer_gen
    action VARCHAR(100) NOT NULL, -- generate_jd, screen_candidates, analyze_video, etc.

    -- Related entities for filtering/lookup
    entity_type VARCHAR(50), -- job, candidate, application, assessment, offer
    entity_id UUID,

    -- Full input/output for debugging and audit
    input_data JSONB,
    output_data JSONB,

    -- Performance and cost tracking
    tokens_used INTEGER,
    latency_ms INTEGER,
    model_used VARCHAR(50),

    -- Execution status
    status VARCHAR(50) DEFAULT 'success', -- success, error, partial
    error_message TEXT,
    error_details JSONB,

    -- Who triggered the agent
    triggered_by UUID REFERENCES public.profiles(id),

    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================
-- INDEXES
-- ============================================

-- Jobs: Common query patterns
CREATE INDEX idx_jobs_status ON public.jobs(status);
CREATE INDEX idx_jobs_created_by ON public.jobs(created_by);
CREATE INDEX idx_jobs_created_at ON public.jobs(created_at DESC);

-- Candidates: Email lookup and listing
CREATE INDEX idx_candidates_email ON public.candidates(email);
CREATE INDEX idx_candidates_created_at ON public.candidates(created_at DESC);

-- Applications: Pipeline views and candidate lookup
CREATE INDEX idx_applications_job_id ON public.applications(job_id);
CREATE INDEX idx_applications_candidate_id ON public.applications(candidate_id);
CREATE INDEX idx_applications_status ON public.applications(status);
CREATE INDEX idx_applications_screening_score ON public.applications(screening_score DESC);

-- Assessments: Lookup and status filtering
CREATE INDEX idx_assessments_application_id ON public.assessments(application_id);
CREATE INDEX idx_assessments_status ON public.assessments(status);
CREATE INDEX idx_assessments_access_token ON public.assessments(access_token);

-- Offers: Application lookup and status
CREATE INDEX idx_offers_application_id ON public.offers(application_id);
CREATE INDEX idx_offers_status ON public.offers(status);

-- Agent logs: Filtering and analytics
CREATE INDEX idx_agent_logs_agent_type ON public.agent_logs(agent_type);
CREATE INDEX idx_agent_logs_entity ON public.agent_logs(entity_type, entity_id);
CREATE INDEX idx_agent_logs_created_at ON public.agent_logs(created_at DESC);

-- ============================================
-- ROW LEVEL SECURITY (RLS)
-- ============================================
--
-- Security Model Overview:
-- - All tables have RLS enabled to prevent unauthorized access
-- - authenticated role: Logged-in users (recruiters, hiring managers)
-- - service_role: Backend services with elevated privileges
-- - anon role: Not granted access to any tables (except token-based assessment access)
--
-- Current implementation uses organization-wide access for authenticated users.
-- For stricter multi-tenant isolation, policies should check company_id.
-- See 002_v2_schema.sql for company-scoped policies.
-- ============================================

-- Enable RLS on all tables
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.candidates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.assessments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.offers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agent_logs ENABLE ROW LEVEL SECURITY;

-- ============================================
-- PROFILES POLICIES
-- ============================================
-- Profiles are user metadata. All authenticated users can view profiles
-- for collaboration (seeing who created a job, assigned to a candidate, etc.)
-- Users can only update their own profile.

CREATE POLICY "profiles_select_authenticated"
    ON public.profiles FOR SELECT
    TO authenticated
    USING (true);
-- NOTE: This allows all authenticated users to see all profiles.
-- For stricter isolation, filter by company_id when implemented.

CREATE POLICY "profiles_update_own"
    ON public.profiles FOR UPDATE
    TO authenticated
    USING (auth.uid() = id)
    WITH CHECK (auth.uid() = id);
-- Users can only update their own profile record.

-- ============================================
-- JOBS POLICIES
-- ============================================
-- Jobs are shared within the organization. All authenticated users can
-- view, create, and update jobs. In a multi-tenant setup, add company_id filtering.

CREATE POLICY "jobs_select_authenticated"
    ON public.jobs FOR SELECT
    TO authenticated
    USING (true);
-- All authenticated users can view all jobs.
-- CONSIDERATION: Add company_id filter for multi-tenant:
-- USING (created_by IN (SELECT id FROM profiles WHERE company_id = current_user_company_id()))

CREATE POLICY "jobs_insert_authenticated"
    ON public.jobs FOR INSERT
    TO authenticated
    WITH CHECK (true);
-- Any authenticated user can create jobs.
-- created_by should be set to auth.uid() by the application.

CREATE POLICY "jobs_update_authenticated"
    ON public.jobs FOR UPDATE
    TO authenticated
    USING (true);
-- All authenticated users can update jobs.
-- CONSIDERATION: Restrict to created_by = auth.uid() OR role = 'admin'

-- ============================================
-- CANDIDATES POLICIES
-- ============================================
-- Candidates are shared applicant records. All recruiters need access
-- to manage the talent pool effectively.

CREATE POLICY "candidates_select_authenticated"
    ON public.candidates FOR SELECT
    TO authenticated
    USING (true);
-- All authenticated users can view all candidates.

CREATE POLICY "candidates_insert_authenticated"
    ON public.candidates FOR INSERT
    TO authenticated
    WITH CHECK (true);
-- Any authenticated user can create candidate records.

CREATE POLICY "candidates_update_authenticated"
    ON public.candidates FOR UPDATE
    TO authenticated
    USING (true);
-- All authenticated users can update candidate records.
-- CONSIDERATION: Add audit trail via triggers for compliance.

-- ============================================
-- APPLICATIONS POLICIES
-- ============================================
-- Applications link candidates to jobs. Full team access needed
-- for pipeline management and collaboration.

CREATE POLICY "applications_select_authenticated"
    ON public.applications FOR SELECT
    TO authenticated
    USING (true);

CREATE POLICY "applications_insert_authenticated"
    ON public.applications FOR INSERT
    TO authenticated
    WITH CHECK (true);

CREATE POLICY "applications_update_authenticated"
    ON public.applications FOR UPDATE
    TO authenticated
    USING (true);

-- ============================================
-- ASSESSMENTS POLICIES
-- ============================================
-- Assessments contain sensitive evaluation data. Team access is needed
-- for review and decision making. Candidate access is via token (handled separately).

CREATE POLICY "assessments_select_authenticated"
    ON public.assessments FOR SELECT
    TO authenticated
    USING (true);

CREATE POLICY "assessments_insert_authenticated"
    ON public.assessments FOR INSERT
    TO authenticated
    WITH CHECK (true);

CREATE POLICY "assessments_update_authenticated"
    ON public.assessments FOR UPDATE
    TO authenticated
    USING (true);

-- NOTE: Candidate access to their own assessment is handled via access_token
-- validation in the application layer, not RLS policies.

-- ============================================
-- OFFERS POLICIES
-- ============================================
-- Offers contain sensitive compensation data. Access should potentially
-- be restricted to specific roles in production.

CREATE POLICY "offers_select_authenticated"
    ON public.offers FOR SELECT
    TO authenticated
    USING (true);
-- CONSIDERATION: Restrict to role IN ('recruiter', 'hiring_manager', 'admin')

CREATE POLICY "offers_insert_authenticated"
    ON public.offers FOR INSERT
    TO authenticated
    WITH CHECK (true);

CREATE POLICY "offers_update_authenticated"
    ON public.offers FOR UPDATE
    TO authenticated
    USING (true);

-- ============================================
-- AGENT LOGS POLICIES
-- ============================================
-- Agent logs are system audit records. Only service_role can insert
-- (from backend), but authenticated users can view for transparency.

CREATE POLICY "agent_logs_select_authenticated"
    ON public.agent_logs FOR SELECT
    TO authenticated
    USING (true);
-- Allow all authenticated users to view agent activity for debugging/audit.

CREATE POLICY "agent_logs_insert_service"
    ON public.agent_logs FOR INSERT
    TO service_role
    WITH CHECK (true);
-- Only backend services (service_role) can create log entries.
-- This prevents users from spoofing agent activity.

-- ============================================
-- FUNCTIONS & TRIGGERS
-- ============================================

-- Function: Automatically update updated_at timestamp on row modification
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply updated_at trigger to all relevant tables
CREATE TRIGGER set_updated_at_profiles
    BEFORE UPDATE ON public.profiles
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

CREATE TRIGGER set_updated_at_jobs
    BEFORE UPDATE ON public.jobs
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

CREATE TRIGGER set_updated_at_candidates
    BEFORE UPDATE ON public.candidates
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

CREATE TRIGGER set_updated_at_applications
    BEFORE UPDATE ON public.applications
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

CREATE TRIGGER set_updated_at_assessments
    BEFORE UPDATE ON public.assessments
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

CREATE TRIGGER set_updated_at_offers
    BEFORE UPDATE ON public.offers
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

-- Function: Create profile automatically when user signs up
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (id, email, full_name)
    VALUES (
        NEW.id,
        NEW.email,
        NEW.raw_user_meta_data->>'full_name'
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
-- SECURITY DEFINER allows this function to insert into profiles
-- even though the trigger runs before the user has authenticated.

-- Trigger: Auto-create profile on user signup
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_new_user();

-- Function: Generate secure access token for candidate assessments
CREATE OR REPLACE FUNCTION public.generate_assessment_token()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.access_token IS NULL THEN
        NEW.access_token = encode(gen_random_bytes(32), 'hex');
        NEW.token_expires_at = NOW() + INTERVAL '7 days';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_assessment_token
    BEFORE INSERT ON public.assessments
    FOR EACH ROW
    EXECUTE FUNCTION public.generate_assessment_token();

-- ============================================
-- STORAGE BUCKETS (Reference)
-- ============================================
-- These buckets should be created via Supabase Dashboard or API:
--
-- CREATE POLICY for storage.objects would go here, but bucket creation
-- is typically done via the Supabase dashboard. Reference configuration:
--
-- Bucket: resumes (private)
--   - Purpose: Store candidate resume files
--   - Access: Authenticated users can upload/download
--
-- Bucket: videos (private)
--   - Purpose: Store assessment video recordings
--   - Access: Authenticated users and token-based candidate access
--
-- Bucket: documents (private)
--   - Purpose: Store offer letters, contracts, etc.
--   - Access: Authenticated users only
